defender_cls: GoalPriorityDefender
defender_name: GoalPriority
defense_type: selfremind
target_llm_config:
  device_map: cuda:0
  llm_type: HuggingFaceLLM
  model_name: Qwen/Qwen2.5-7B-Instruct
target_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  seed: 42
  temperature: 1.0
