defender_cls: GoalPriorityDefender
defender_name: GoalPriority
target_llm_config: 
  llm_type: HuggingFaceLLM
  model_name: Qwen/Qwen2-7B-Instruct
  device_map: cuda:3 
target_llm_gen_config: 
  max_n_tokens: 100_000
  temperature: 1.0
  logprobs: false
  seed: 42

defense_type: "priority"