defender_cls: NoneDefender
target_llm_config:
  llm_type: OpenAiLLM
  model_name: meta-llama/Meta-Llama-3.1-70B-Instruct
target_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  seed: null
  temperature: 1.0
