defender_cls: PerplexityFilterDefender
filter_llm_config:
  llm_type: OpenAiLLM
  model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
filter_llm_gen_config:
  logprobs: true
  max_n_tokens: 0
  seed: null
  temperature: 1.0
target_llm_config:
  llm_type: OpenAiLLM
  model_name: meta-llama/Meta-Llama-3.1-70B-Instruct
target_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  seed: null
  temperature: 1.0
threshold: 500
