defender_cls: RPODefender
defender_name: RPO
target_llm_config:
  device_map: cuda:0
  llm_type: HuggingFaceLLM
  model_name: meta-llama/Llama-3.2-1B-Instruct
target_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  seed: 42
  temperature: 1.0
