
defender_cls: SelfDefenseDefender
defender_name: SelfDefense
target_llm_config: 
  llm_type: HuggingFaceLLM
  model_name: Qwen/Qwen2-7B-Instruct
  device_map: cuda:3 
target_llm_gen_config: 
  max_n_tokens: 100_000
  temperature: 1.0
  logprobs: false
  seed: 42

judge_config:
  judge_cls: PairLLMJudge
  judge_name: PAIR
  judge_llm_config:
    llm_type: HuggingFaceLLM
    model_name: Qwen/Qwen2-7B-Instruct
    device_map: cuda:4
  judge_llm_gen_config:
    max_n_tokens: 100_000
    temperature: 1.0
    logprobs: false
    seed: 42
judge_score_threshold: 5
