- judge_cls: PairLLMJudge
  judge_llm_config:
    api_key: token-casia-braincog-233
    base_url: http://172.18.131.12:8000/v1
    llm_type: OpenAiChatLLM
    model_name: meta-llama/Meta-Llama-3.1-70B-Instruct
  judge_llm_gen_config:
    logprobs: false
    max_n_tokens: 25
    seed: 42
    temperature: 0.0
- judge_cls: PairLLMJudge
  judge_llm_config:
    api_key: token-casia-braincog-233
    base_url: http://210.75.240.144:3006/v1
    llm_type: OpenAiChatLLM
    model_name: Qwen/Qwen2-72B-Instruct
  judge_llm_gen_config:
    logprobs: false
    max_n_tokens: 25
    seed: 42
    temperature: 0.0
- judge_cls: RuleBasedJudge
