adv_prompts_size: 256
allow_non_ascii: false
attacker_cls: AutoDanAttacker
attacker_name: AutoDan
batch_size: 32
crossover: 0.5
init_adv_prompts_path: ../../panda_guard/role/attacks/autodan/prompt_group.yaml
iter: 5
llm_mutation: false
mutation: 0.01
num_elites: 0.1
num_points: 5
num_steps: 250
target_llm_config:
  device_map: cuda:4
  llm_type: HuggingFaceLLM
  model_name: meta-llama/Llama-3.2-1B-Instruct
target_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  seed: null
  temperature: 1.0
