attacker_cls: ColdAttacker
attacker_name: COLD
cold_config:
  abductive_filterx: false
  batch_size: 1
  constraint_iters: 1000
  control_type: sentiment
  counterfactual_max_ngram: 3
  end: 50
  fp16: true
  frozen_length: 0
  goal_weight: 500
  gs_mean: 0.0
  gs_std: 0.01
  if_zx: false
  init_mode: original
  init_temp: 1
  input_lgt_temp: 1.0
  large_gs_std: 0.1, 0.05, 0.01, 0.001
  large_noise_iters: 50, 200, 500, 1500
  length: 100
  lexical: max
  lexical_variants: false
  lr_nll_portion: 1.0
  max_length: 100
  min_iters: 0
  mode: suffix
  no_cuda: false
  no_loss_rerank: false
  noise_iters: 1
  num_iters: 1000
  output_lgt_temp: 1.0
  prefix_length: 0
  pretrained_model: llama2
  print_every: 2000,
  rej_weight: 100
  rl_output_lgt_temp: 1.0
  rl_topk: 0
  start: 0
  stepsize: 0.1
  stepsize_iters: 1000
  stepsize_ratio: 1
  straight_through: true
  topk: 10
  use_sysprompt: false
  verbose: false
  version: ''
  wandb: false
  win_anneal_iters: 1000
white_box_llm_config:
  llm_type: HuggingFaceLLM
  model_name: meta-llama/Meta-Llama-3.1-70B-Instruct
white_box_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  seed: null
  temperature: 1.0
