add_space_before_target: false
adv_string_init: x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x
  x x x x x
allow_non_ascii: false
attacker_cls: GCGAttacker
attacker_name: GCG
batch_size: null
buffer_size: 0
early_stop: false
filter_ids: true
llm_config:
  device_map: cuda:6
  llm_type: HuggingFaceLLM
  model_name: meta-llama/Llama-3.2-1B-Instruct
llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  seed: null
  temperature: 1.0
mellowmax_alpha: 1.0
n_replace: 1
num_steps: 250
search_width: 512
seed: null
topk: 256
use_mellowmax: false
use_prefix_cache: true
