attacker_cls: GPTFuzzAttacker
attacker_llm_config:
  device_map: cuda:0
  llm_type: HuggingFaceLLM
  model_name: meta-llama/Llama-3.1-8B-Instruct
attacker_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  seed: null
  temperature: 1.0
attacker_name: GPTFuzz
initial_seed: ../../data/GPTFuzz/GPTFuzzer.csv
predict_model: hubert233/GPTFuzz
target_llm_config:
  llm_type: HuggingFaceLLM
  model_name: meta-llama/Llama-3.2-8B-Instruct
target_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  seed: null
  temperature: 1.0
