attacker_cls: "RandomSearchAttacker"
attacker_name: "RandomSearch"

target_llm_config:
  llm_type: "HuggingFaceLLM"
  model_name: "Qwen/Qwen2-7B-Instruct"
target_llm_gen_config:
  max_n_tokens: 150
  temperature: 1.0
  logprobs: True
  seed: 42

max_iterations: 10000
max_restarts: 10
target_str: Sure,
verbose: True
logprob_threshold: -0.5
max_n_to_change: 8

