attacker_cls: ScavAttacker
attacker_name: Scav
optimzed_file_70b: /home/shensicheng/code/panda-guard/data/scav/optimized_instructions_70b.csv
optimzed_file_8b: /home/shensicheng/code/panda-guard/data/scav/optimized_instructions_8b.csv
target_llm_name: meta-llama/llama-3.1-70b-in
