attack_llm_config:
  llm_type: OpenAiLLM
  model_name: Llama-3.1-70B-Instruct
attack_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  temperature: 0.001
attacker_cls: TAPAttacker
attacker_name: TAP
branching_factor: 2
depth: 2
tap_judge_config:
  judge_cls: TAPLLMJudge
  judge_llm_config:
    llm_type: OpenAiLLM
    model_name: Llama-3.1-70B-Instruct
  judge_llm_gen_config:
    logprobs: false
    max_n_tokens: 4096
    temperature: 0.001
  judge_name: TAPJudge
target_llm_config:
  llm_type: OpenAiLLM
  model_name: Llama-3.1-70B-Instruct
target_llm_gen_config:
  logprobs: false
  max_n_tokens: 4096
  temperature: 0.001
target_str: Sure.
width: 2
