attacker:
  attacker_cls: TransferAttacker
  attacker_name: null
defender:
  defender_cls: NoneDefender
  target_llm_config:
    llm_type: OpenAiLLM
    model_name: meta-llama/Meta-Llama-3-70B-Instruct
  target_llm_gen_config:
    logprobs: false
    max_n_tokens: 150
    seed: null
    temperature: 1.0
judges:
- judge_cls: PairLLMJudge
  judge_llm_config:
    llm_type: OpenAiChatLLM
    model_name: gpt-4o-2024-11-20
  judge_llm_gen_config:
    logprobs: false
    max_n_tokens: 25
    seed: 42
    temperature: 0.0
- judge_cls: PairLLMJudge
  judge_llm_config:
    llm_type: OpenAiChatLLM
    model_name: meta-llama/Llama-3.3-70B-Instruct
  judge_llm_gen_config:
    logprobs: false
    max_n_tokens: 25
    seed: 42
    temperature: 0.0
- judge_cls: PairLLMJudge
  judge_llm_config:
    llm_type: OpenAiChatLLM
    model_name: Qwen/Qwen2.5-72B-Instruct
  judge_llm_gen_config:
    logprobs: false
    max_n_tokens: 25
    seed: 42
    temperature: 0.0
- judge_cls: RuleBasedJudge
misc:
  input_file: ../../data/jbb_expanded.csv
  output_file: null
  threads: 1
