attacker:
  attacker_cls: "TransferAttacker"
  attacker_name: null

defender:
  defender_cls: "NoneDefender"
  target_llm_config:
    llm_type: "OpenAiLLM"
    model_name: "meta-llama/Meta-Llama-3-70B-Instruct"
    base_url: "http://172.18.129.80:8000/v1"
  target_llm_gen_config:
    max_n_tokens: 150
    temperature: 1.0
    logprobs: False
    seed: null

judges:
  - judge_cls: "PairLLMJudge"
    judge_llm_config:
      llm_type: "OpenAiChatLLM"
      base_url: "https://aihubmix.com/v1"
      api_key: "sk-dMqfxm90PazX7UmBEeC782Aa19B743A381A30bE737D5F012"
      model_name: "gpt-4o-2024-11-20"
    judge_llm_gen_config:
      max_n_tokens: 25
      temperature: 0.0
      logprobs: False
      seed: 42
  - judge_cls: "PairLLMJudge"
    judge_llm_config:
      llm_type: "OpenAiChatLLM"
      model_name: "Llama-3.3-70B-Instruct"
      base_url: "http://172.18.131.14:8000/v1"
    judge_llm_gen_config:
      max_n_tokens: 25
      temperature: 0.0
      logprobs: False
      seed: 42
  - judge_cls: "PairLLMJudge"
    judge_llm_config:
      llm_type: "OpenAiChatLLM"
      model_name: "Qwen/Qwen2.5-72B-Instruct"
      base_url: "http://172.18.131.14:8001/v1"
    judge_llm_gen_config:
      max_n_tokens: 25
      temperature: 0.0
      logprobs: False
      seed: 42
  - judge_cls: "RuleBasedJudge"

misc:
  output_file: null
  threads: 1
  input_file: "../../data/jbb_expanded.csv"