attacker:
  attacker_cls: TransferAttacker
  attacker_name: DEV_MODE_Ranti
defender:
  defender_cls: NoneDefender
  target_llm_config:
    device_map: cuda:3
    llm_type: HuggingFaceLLM
    model_name: Qwen/Qwen2.5-3B-Instruct
  target_llm_gen_config:
    logprobs: false
    max_n_tokens: 150
    seed: null
    temperature: 1.0
judges: null
misc:
  input_file: ../../data/jbb_expanded.csv
  output_file: null
  threads: 1
