attacker:
  attacker_cls: TransferAttacker
  attacker_name: PAIR
defender:
  defender_cls: PerplexityFilterDefender
  filter_llm_config:
    base_url: http://172.18.131.16:8000/v1
    llm_type: OpenAiLLM
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
  filter_llm_gen_config:
    logprobs: true
    max_n_tokens: 0
    seed: null
    temperature: 1.0
  target_llm_config:
    device_map: cuda:3
    llm_type: HuggingFaceLLM
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
  target_llm_gen_config:
    logprobs: false
    max_n_tokens: 150
    seed: null
    temperature: 1.0
  threshold: 500
judges: null
misc:
  input_file: ../../data/jbb_expanded.csv
  output_file: null
  threads: 1
