attacker:
  attacker_cls: TransferAttacker
  attacker_name: null
defender:
  defender_cls: NoneDefender
  target_llm_config:
    device_map: cuda:2
    llm_type: HuggingFaceLLM
    model_name: microsoft/Phi-3-mini-4k-instruct
  target_llm_gen_config:
    logprobs: false
    max_n_tokens: 2048
    seed: null
    temperature: 1.0
misc:
  input_file: null
  output_file: null
  threads: 1
