defender_cls: GradSafeDefender
defender_name: GradSafe
target_llm_config:
  device_map: cuda:3
  llm_type: HuggingFaceLLM
  model_name: meta-llama/Llama-3.2-3B-Instruct
target_llm_gen_config:
  logprobs: false
  max_n_tokens: 128
  seed: 42
  temperature: 1.0
unsafe_threshold: 0.25
