attacker_cls: "ReNeLLMAttacker"
attacker_name: "ReNeLLM"

# rewrite llm configs
rewrite_llm_config:
  llm_type: "HuggingFaceLLM"
  model_name: "meta-llama/Llama-3.1-8B-Instruct"
  device_map: cuda:1

rewrite_llm_gen_config:
  max_n_tokens: 1000
  temperature: 1.0
  logprobs: False
  seed: null

# target llm configs
target_llm_config:
  llm_type: "HuggingFaceLLM"
  model_name: "meta-llama/Llama-3.1-8B-Instruct"
  device_map: cuda:2

target_llm_gen_config:
  max_n_tokens: 1000
  temperature: 1.0
  logprobs: False
  seed: null

# judge llm configs
judge_llm_config:
  llm_type: "HuggingFaceLLM"
  model_name: "meta-llama/Llama-3.1-8B-Instruct"
  device_map: cuda:3

judge_llm_gen_config:
  max_n_tokens: 1000
  temperature: 1.0
  logprobs: False
  seed: null