attacker:
  attacker_cls: "TransferAttacker"
  attacker_name: null

defender:
  defender_cls: "NoneDefender"
  target_llm_config:
    llm_type: "OpenAiLLM"
    model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    base_url: "http://172.18.129.86:8001/v1"
  target_llm_gen_config:
    max_n_tokens: 4096
    temperature: 1.0
    logprobs: False
    seed: null

misc:
  output_file: null
  threads: 1
  input_file: null