attacker:
  attacker_cls: TransferAttacker
  attacker_name: PAIR
defender:
  defender_cls: GoalPriorityDefender
  defender_name: GoalPriority
  defense_type: priority_llama
  target_llm_config:
    device_map: cuda:0
    llm_type: HuggingFaceLLM
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
  target_llm_gen_config:
    logprobs: false
    max_n_tokens: 150
    seed: null
    temperature: 1.0
judges: null
misc:
  input_file: ../../data/jbb_expanded.csv
  output_file: null
  threads: 1
