attacker:
  attacker_cls: TransferAttacker
  attacker_name: DEV_MODE_Ranti
defender:
  defender_cls: SemanticSmoothLLMDefender
  perturbation_llm_config:
    base_url: http://172.18.131.16:8000/v1
    llm_type: OpenAiLLM
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
  perturbation_llm_gen_config:
    logprobs: false
    max_n_tokens: 300
    seed: null
    temperature: 1.0
  target_llm_config:
    device_map: cuda:6
    llm_type: HuggingFaceLLM
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
  target_llm_gen_config:
    logprobs: false
    max_n_tokens: 150
    seed: null
    temperature: 1.0
judges: null
misc:
  input_file: ../../data/jbb_expanded.csv
  output_file: null
  threads: 1
