attacker:
  attacker_cls: "TransferAttacker"
  attacker_name: "past_tense"

defender:
  defender_cls: "SemanticSmoothLLMDefender"
  target_llm_config:
    llm_type: "OpenAiLLM"
    model_name: "meta-llama/Meta-Llama-3.1-70B-Instruct"
    base_url: "http://172.18.129.80:8000/v1"
  target_llm_gen_config:
    max_n_tokens: 150
    temperature: 1.0
    logprobs: False
    seed: null
  perturbation_llm_config:
    llm_type: "OpenAiLLM"
    model_name: "meta-llama/Meta-Llama-3.1-70B-Instruct"
    base_url: "http://172.18.129.80:8000/v1"
  perturbation_llm_gen_config:
    max_n_tokens: 150
    temperature: 1.0
    logprobs: False
    seed: null

judges:
  - judge_cls: "PairLLMJudge"
    judge_llm_config:
      llm_type: "OpenAiLLM"
      model_name: "meta-llama/Meta-Llama-3.1-70B-Instruct"
      base_url: "http://172.18.129.80:8000/v1"
    judge_llm_gen_config:
      max_n_tokens: 25
      temperature: 0.0
      logprobs: False
      seed: 42
  - judge_cls: "RuleBasedJudge"

misc:
  output_file: null
  threads: 1
  input_file: "../data/jbb_expanded.csv"