Qwen/Qwen2-7B-Instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.131.18:8000/v1"

meta-llama/Meta-Llama-3-8B-Instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.131.2:8000/v1"

mistralai/Mistral-7B-Instruct-v0.3:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.131.18:8009/v1"

google/gemma-2-9b-it:
  llm_type: "OpenAiLLM"
#  base_url: "http://172.18.131.18:8003/v1"
  base_url: "http://localhost:233/v1"
  api_key: "token-casia-braincog-233"


microsoft/Phi-3-mini-4k-instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.131.18:8004/v1"


meta-llama/Meta-Llama-3.1-8B-Instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.131.18:8001/v1"


Qwen/Qwen1.5-7B-Chat:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.131.18:8006/v1"

#meta-llama/Meta-Llama-3-70B-Instruct:
#  llm_type: "OpenAiLLM"
#  base_url: "http://172.18.131.4:8000/v1"
#  api_key: "token-casia-braincog-233"
#
#Qwen/Qwen2-72B-Instruct:
#  llm_type: "OpenAiLLM"
#  base_url: "http://172.18.131.6:8000/v1"
#  api_key: "token-casia-braincog-233"


##microsoft/Phi-3-small-8k-instruct:
##  llm_type: "OpenAiLLM"
##  base_url: "http://172.18.131.18:8006/v1"
#