Qwen/Qwen2-7B-Instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.129.86:8000/v1"

meta-llama/Meta-Llama-3-8B-Instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.129.86:8002/v1"

mistralai/Mistral-7B-Instruct-v0.3:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.129.86:8003/v1"

microsoft/Phi-3-medium-4k-instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.129.86:8005/v1"

microsoft/Phi-3-mini-4k-instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.129.86:8006/v1"

# Removed
meta-llama/Meta-Llama-3.1-8B-Instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.129.86:8001/v1"

microsoft/Phi-3-small-8k-instruct:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.129.86:8004/v1"

Qwen/Qwen1.5-7B-Chat:
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.129.86:8007/v1"

#meta-llama/Meta-Llama-3.1-70B-Instruct:
#  llm_type: "OpenAiLLM"
#  base_url: "http://172.18.129.80:8000/v1"
