Qwen/Qwen1.5-7B-Chat:
  llm_type: OpenAiLLM
Qwen/Qwen2-72B-Instruct:
  llm_type: OpenAiLLM
deepseek-reasoner:
  llm_type: OpenAiChatLLM
google/gemma-2-2b-it:
  llm_type: OpenAiLLM
google/gemma-2-9b-it:
  llm_type: OpenAiLLM
meta-llama/Meta-Llama-3-70B-Instruct:
  llm_type: OpenAiLLM
meta-llama/Meta-Llama-3-8B-Instruct:
  llm_type: OpenAiLLM
meta-llama/Meta-Llama-3.1-8B-Instruct:
  llm_type: OpenAiLLM
microsoft/Phi-3-mini-4k-instruct:
  llm_type: OpenAiLLM
