attacker:
  attack_llm_config:
    api_key: token-casia-braincog-233
    base_url: http://172.18.131.14:8002/v1
    llm_type: OpenAiLLM
    model_name: Llama-3.1-70B-Instruct
  attack_llm_gen_config:
    logprobs: false
    max_n_tokens: 100000
    temperature: 0.001
  attacker_cls: TAPAttacker
  attacker_name: TAP
  branching_factor: 2
  depth: 2
  tap_judge_config:
    judge_cls: TAPLLMJudge
    judge_llm_config:
      api_key: token-casia-braincog-233
      base_url: http://172.18.131.14:8002/v1
      llm_type: OpenAiLLM
      model_name: Llama-3.1-70B-Instruct
    judge_llm_gen_config:
      logprobs: false
      max_n_tokens: 100000
      temperature: 0.001
    judge_name: TAPJudge
  target_llm_config:
    api_key: token-casia-braincog-233
    base_url: http://172.18.131.14:8002/v1
    llm_type: OpenAiLLM
    model_name: Llama-3.1-70B-Instruct
  target_llm_gen_config:
    logprobs: false
    max_n_tokens: 100000
    temperature: 0.001
  target_str: Sure.
  width: 2
defender:
  defender_cls: NoneDefender
  target_llm_config:
    llm_type: HuggingFaceLLM
    model_name: Qwen/Qwen2.5-1.5B-Instruct
  target_llm_gen_config:
    logprobs: false
    max_n_tokens: 150
    seed: null
    temperature: 1.0
judges: null
misc:
  input_file: ../../data/jbb_expanded.csv
  output_file: null
  threads: 1
