attacker:
  attacker_cls: TransferAttacker
  attacker_name: GCG
defender:
  batch_inference: true
  defender_cls: SmoothLLMDefender
  num_perturbations: 3
  perturbation_ratio: 0.1
  perturbation_type: swap
  target_llm_config:
    device_map: cuda:7
    llm_type: HuggingFaceLLM
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
  target_llm_gen_config:
    logprobs: false
    max_n_tokens: 150
    seed: null
    temperature: 1.0
judges: null
misc:
  input_file: ../../data/jbb_expanded.csv
  output_file: null
  threads: 1
